name: Release

on:
  push:
    branches:
      - main
    paths:
      - lib/boring_avatars/version.rb
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: r7kamura/workflows/.github/workflows/gem-release.yml@main
